name: Setup Environment
description: Sets up development environment.

# Required Permissions:
#   - contents: read

runs:
  using: 'composite'

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v6
      with:
        cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: 'package.json'

    - name: Install dependencies
      run: pnpm install
      shell: bash
